dist: trusty
sudo: required

os:
  - linux
  - osx

language: python

cache:
  apt: true
  # We use three different cache directory
  # to work around a Travis bug with multi-platform cache
  directories:
  - $HOME/.cache/pip
  - $HOME/download

env:
  global:
    # Directory where tests are run from
    - TEST_DIR=/tmp/test_dir/
    - MODULE=grakel
    - TWINE_USERNAME=ysig
    - DEPLOY_WHEEL=true

  matrix:
    - DISTRIB="conda" PYTHON_VERSION="2.7"
      NUMPY_VERSION="1.14.2" SCIPY_VERSION="1.0.1" CYTHON_VERSION="0.27.3"
    - DISTRIB="conda" PYTHON_VERSION="3.5" COVERAGE="true"
      NUMPY_VERSION="1.14.2" SCIPY_VERSION="1.0.1" CYTHON_VERSION="0.27.3"
    - DISTRIB="conda" PYTHON_VERSION="3.6" COVERAGE="true"
      NUMPY_VERSION="1.14.2" SCIPY_VERSION="1.0.1" CYTHON_VERSION="0.27.3"

install:
  - source ci_scripts/travis/install.sh
  - flake8 --version
  - flake8 grakel

script: bash ci_scripts/travis/test.sh

after_success:
    - source ci_scripts/travis/success.sh
    - |
      if [[ "$DEPLOY_WHEEL" == "true" ]]; then
        cd $TRAVIS_BUILD_DIR
        pip install cibuildwheel==0.7.1
        cibuildwheel --output-dir wheelhouse
        python -m pip install twine
        python -m twine upload wheelhouse/*.whl
      fi
