language: python

cache:
  apt: true
  # We use three different cache directory
  # to work around a Travis bug with multi-platform cache
  directories:
  - $HOME/.cache/pip
  - $HOME/download

env:
  global:
    # Directory where tests are run from
    - TEST_DIR=/tmp/test_dir
    - MODULE=grakel
    - WHEEL_FOLDER=wheelhouse
    - TWINE_USERNAME=ysig
    - DEPLOY_SDIST="false"
    - COVERAGE="false"
    - DEPLOY_WHEEL="false"

matrix:
  include:
    - sudo: required
      services:
        - docker
      env:
        - PIP=pip
        - PYTHON=python
        - CIBW_BUILD="cp27-manylinux1_x86_64"
        - DEPLOY_SDIST="true"
    - sudo: required
      services:
        - docker
      env:
        - PIP=pip
        - PYTHON=python
        - CIBW_BUILD="cp27-manylinux1_i686"
    - sudo: required
      services:
        - docker
      env:
        - PIP=pip
        - PYTHON=python
        - CIBW_BUILD="cp35-*"
    - sudo: required
      services:
        - docker
      env:
        - PIP=pip
        - PYTHON=python
        - CIBW_BUILD="cp36-*"
    - os: osx
      sudo: required
      language: generic
      env:
        - PIP=pip2
        - PYTHON=python2
        - COVERAGE="true"
        - CIBW_BUILD="cp27-macosx_10_6_intel"
    - os: osx
      sudo: required
      language: generic
      env:
        - PIP=pip2
        - PYTHON=python2
        - CIBW_BUILD="cp35-macosx_10_6_intel"
    - os: osx
      sudo: required
      language: generic
      env:
        - PIP=pip2
        - PYTHON=python2
        - CIBW_BUILD="cp36-macosx_10_6_intel"
script:
  - $PIP install flake8 --upgrade && flake8 $TRAVIS_BUILD_DIR/grakel
  - $PIP install cibuildwheel
  - export CIBW_ENVIRONMENT="TEST_DIR=$TEST_DIR MODULE=$MODULE COVERAGE=$COVERAGE";
  - IFS= ; export CIBW_BEFORE_BUILD="$(cat ci_scripts/travis/install.sh)";
  - |
    if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
        $PIP install numpy cython --upgrade;
        IFS= ; export CIBW_TEST_COMMAND="nosetests $MODULE";
    else
        IFS= ; export CIBW_TEST_COMMAND="$(cat ci_scripts/travis/test.sh)";
    fi
  - cibuildwheel --output-dir $WHEEL_FOLDER

after_success:
  - bash ci_scripts/travis/success.sh
