version: 2
jobs:
  python3:
    docker:
      - image: circleci/python:3.5
    steps:
      - checkout
      - run: sudo -E apt-get -yq remove texlive-binaries --purge
      - run: sudo apt-get update
      - run: sudo apt-get install libatlas-dev libatlas3gf-base
      - run: sudo apt-get install build-essential python-dev python-setuptools
      - run: sudo pip install --upgrade numpy
      - run: sudo pip install --upgrade scipy matplotlib setuptools nose coverage sphinx pillow sphinx-gallery sphinx_rtd_theme sphinxcontrib-bibtex nb2plots
      - run: sudo -E apt-get -yq update
      - run: sudo -E apt-get -yq --no-install-suggests --no-install-recommends --force-yes install dvipng texlive-latex-base texlive-latex-extra
      - run: sudo pip install --upgrade tqdm
      - run: sudo pip install --upgrade cython numpydoc
      - run: sudo pip install --upgrade scikit-learn
      - run: sudo pip install --upgrade cvxopt
      - run: sudo python setup.py clean
      - run: sudo python setup.py develop
      - run: set -o pipefail && cd doc && make html 2>&1 | tee ~/log.txt
      - run: cat ~/log.txt && if grep -q "Traceback (most recent call last):" ~/log.txt; then false; else true; fi
      - store_artifacts:
          path: doc/_build/html
          destination: doc
      - store_artifacts:
          path: ~/log.txt
          destination: log.txt
      - persist_to_workspace:
          root: doc/_build/html
          paths: .

  deploy:
    docker:
      - image: circleci/python:3.5
    environment:
      # The github organization or username of the repository which hosts the
      # project and documentation.
      - USERNAME: "ysig"

      # The repository where the documentation will be hosted
      - DOC_REPO: "GraKeL"

      # The base URL for the Github page where the documentation will be hosted
      - DOC_URL: "dev"

      # The email is to be used for commits in the Github Page
      - EMAIL: "y.siglidis@gmail.com"
    steps:
      - checkout
      - attach_workspace:
          at: doc/_build/html
      - deploy:
          command: bash ./ci_scripts/circleci/push_doc.sh

workflows:
  version: 2
  build-doc-and-deploy:
    jobs:
      - python3
      - deploy:
          requires:
            - python3
          filters:
            branches:
              only: develop
